#ifndef KERNEL_INCLUDED_INTERRUPTS_CONFIG
#define KERNEL_INCLUDED_INTERRUPTS_CONFIG 1

#define INT_EXCEPTION_COUNT 32
#define INT_HWINT_COUNT     16
#define INT_TOTAL_COUNT     (INT_EXCEPTION_COUNT + INT_HWINT_COUNT)

#define INT_EXCEPTION_FIRST 0
#define INT_EXCEPTION_LAST (INT_EXCEPTION_FIRST + INT_EXCEPTION_COUNT - 1)

#define INT_HWINT_FIRST (INT_EXCEPTION_LAST + 1)
#define INT_HWINT_LAST  (INT_HWINT_FIRST + INT_HWINT_COUNT - 1)

#define INT_SYSCALL 0x80

#endif
