#include "config.h"

%include "interrupt.asm"

INTERRUPT_COMMON hwint_handler, GDT_KERNEL_DS_SELECTOR

INTERRUPT_NOERRCODE 32 ; Programmable Interval Timer
INTERRUPT_NOERRCODE 33 ; Keyboard
INTERRUPT_NOERRCODE 34 ; Slave PIC
INTERRUPT_NOERRCODE 35 ; COM 2/4
INTERRUPT_NOERRCODE 36 ; COM 1/3
INTERRUPT_NOERRCODE 37 ; LPT 2
INTERRUPT_NOERRCODE 38 ; Floppy Drive Controller
INTERRUPT_NOERRCODE 39 ; LPT 1

INTERRUPT_NOERRCODE 40 ; Real Time Clock
INTERRUPT_NOERRCODE 41 ; Master PIC
INTERRUPT_NOERRCODE 42 ; Reserved
INTERRUPT_NOERRCODE 43 ; Reserved
INTERRUPT_NOERRCODE 44 ; Reserved
INTERRUPT_NOERRCODE 45 ; Coprocessor exception
INTERRUPT_NOERRCODE 46 ; Hard Drive Controller
INTERRUPT_NOERRCODE 47 ; Reserved
